.PHONY: clean All

All:
	@echo "----------Building project:[ first - Debug ]----------"
	@cd "first" && "$(MAKE)" -f  "first.mk"
clean:
	@echo "----------Cleaning project:[ first - Debug ]----------"
	@cd "first" && "$(MAKE)" -f  "first.mk" clean
