.PHONY: clean All

All:
	@echo "----------Building project:[ mine - Debug ]----------"
	@cd "mine" && "$(MAKE)" -f  "mine.mk"
clean:
	@echo "----------Cleaning project:[ mine - Debug ]----------"
	@cd "mine" && "$(MAKE)" -f  "mine.mk" clean
